title: RHEL Performance Guide
description: A complete guide to RHEL performance tuning and monitoring

remote_theme: clearpathrobotics/jekyll-rtd-theme

defaults:
  - scope:
      path: "README.md"
    values:
      permalink: "index.html"
