title: RHEL Performance Guide
lang: en
description: A complete guide to RHEL performance tuning and monitoring

remote_theme: rundocs/jekyll-rtd-theme

#plugins:
#  - jekyll-relative-links

#readme_index:
#  with_frontmatter: true

#relative_links:
#  enabled:     true
#  collections: false

#exclude:
#  - Gemfile
#  - Gemfile.lock
